### ISSUE TITLE
install with composer fails

### ISSUE THREAD

**Issue by Lemmork** [TYPO3-Surf-CMS/Surf.CMS#12]
Installing typo3/surf-cms with composer does not install Packages/Application/TYPO3.Surf.CMS, which is the important part of this repository.
Perhaps this results from the .gitignore file?

**Comment by helhum** [comment]
Thanks. Fixed. You may want to consider to use he new Surf packages which works completely independent from Flow and also distributed as phar file. https://github.com/TYPO3/Surf
