### ISSUE TITLE
Seperate distribution and tasks

### ISSUE THREAD

**Issue by astehlik** [TYPO3-Surf-CMS/Surf.CMS#2]
Would it be possible to split the distribution package and the surf tasks (which actually have their own composer.json file already)?

Or is it done this way on purpose?

Cheers,
Alex

**Comment by helhum** [comment]
I've done this on purpose. It simplifies the publishing of the package drastically.

Eventually, all the tasks of this package will be merged into Surf anyway. Until then, I'd like to keep  this as is...
